# Semantic Network

# The code below produces a one-category semantic net
# (e.g. concerns named with other concerns) from the dictionary-matches
# generated by Quanteda applied to Hansard in 
# quanteda-code-for-app-2.R.

# DEVELOPMENT: 
# 1) The command to create pairs1 can easily overheat with data too large.
# It should be rewritten to (maybe) test some limit of df size, 
# split df into decades, run each decade separately in a for loop.
# 2) I know  no good way to reliably narrow down the number of entities to a visualizable
# set of nodes and edges to graph for g21.  I'd like to narrow tidygraph1 to a representation
# of some 100-200 entities.  You'll see my attempt to do so, which doesn't really work.
# 3) Probably this script should be run in advance to spit out static csv's for major targets 
# (city-concern, nation-concern, concern-office, etc.).  Perhaps the graph visualization 
# should also be pre-computed.  There's a launcher script in quanteda-code-for-app-2.R, but
# perhaps it needs additions, for example if g21 should be precomputed before being
# graphed, or if it should begin with the csv files saved towards the end of this script?  
# What is the best kind of architecture?
# 4) please review the "nonbritain" search for g22. the goal is to map nodes whose geography 
# is not Britain.  





if(target == "text"){
  
  
  dfcount <- df %>% dplyr::count(sentence_id) #group_by(sentence_id) %>%
  #mutate(n = n(term))
  
  dfcount %>% ggplot(aes(x = n)) +
    geom_histogram()
  
  toolong <- dfcount %>% filter(n > 25) %>%
    left_join(df)
  
  df <- df %>% anti_join(toolong, wt = sentence_id)
  
  
  parallel <- TRUE
  setup_parallel()
  allresults <- data.frame()
  
  for(firstyear in seq(from = 1800, to = 1908, by = 10)){
    lastyear <- firstyear + 9
    df0 <- df %>% filter(year >= firstyear) %>%
      filter(year <= lastyear)
    edges <- foreach(m = unique(df$year),#max(df$year),
                     .combine = rbind,
                     .packages = c("dplyr", "tidyr")) %dopar% {   # in 1806:1911){
                       
                       df1 <- df0 %>% #filter(year >= 1800+(d1*10)) %>%
                         #<= 1809+(d1*10))#
                         filter(year == m) 
                       #### import results and turn into a network.
                       # import results and limit to those in classifier
                       terms <- df1 %>%
                         distinct(speechdate, debate_id, sentence_id, term, count) %>%
                         dplyr::group_by(debate_id, sentence_id, term) %>%
                         dplyr::summarize(count = sum(count)) %>%
                         ungroup() %>%
                         ungroup() 
                       
                       uniqueterms <- df1 %>%
                         group_by(term) %>% 
                         sample_n(1) %>% ungroup() %>%
                         select(term, kind, geography, empire) 
                       
                       termsinpairs <- terms %>%
                         dplyr::group_by(sentence_id) %>%
                         dplyr::mutate(numterms = dplyr::n()) %>%
                         ungroup() %>%
                         filter(numterms > 1) %>%
                         select(-numterms)
                       
                       # get pairwise counts
                       # assemble a tibble with all the pairs
                       pairs1 <- termsinpairs %>% 
                         # mutate(edgeid = paste0(debate, "-", speechdate)) %>%
                         # select(edgeid, term) %>%
                         dplyr::group_by(sentence_id) %>% 
                         expand(sentence_id, from = term, to = term) %>% 
                         filter(from < to) %>%
                         ungroup()       
                       
                       nodes <- uniqueterms %>% 
                         dplyr::left_join(terms) %>% #rbind(results1, results2) %>% 
                         # group_by(term) %>% sample_n(1) %>% ungroup() %>%
                         dplyr::group_by(kind, empire, geography, term) %>%
                         dplyr::summarize(count = sum(count)) %>%
                         #rename(node = term) %>%
                         arrange(desc(count)) %>% ungroup() %>% ungroup() 
                       
                       # create edges
                       edges <- pairs1 %>%
                         filter(!is.na(from)) %>%
                         filter(!is.na(to)) %>%
                         dplyr::count(from, to) %>%
                         dplyr::rename(weight = n) %>%
                         filter(weight > 0) %>%
                         filter((from %in% uniqueterms$term)&(to %in% uniqueterms$term))
                       
                       
                       
                       # count connections
                       connections <- edges %>%
                         dplyr::group_by(from) %>%
                         dplyr::summarize(connections = dplyr::n(), total_weight = sum(weight)) %>%
                         dplyr::rename(node = from)
                       
                       
                       # retain only the nodes that are in edge pairs
                       nodes <- nodes %>% 
                         dplyr::rename(node = term) %>%
                         filter((node %in% edges$from)|(node %in% edges$to))
                       
                       nodes <- nodes %>% dplyr::left_join(connections) %>%
                         filter(connections > 0) %>%
                         filter(total_weight > 0)
                       
                       # only the nodes that are in edge pairs
                       nodes <- nodes %>% filter((node %in% edges$from)|(node %in% edges$to))%>%
                         arrange(desc(count)) %>%
                         filter(!is.na(node)) %>%
                         filter(count > 0)  %>%
                         dplyr::mutate(id = row_number())
                       
                       # add id numbers to nodes
                       nodes <- nodes %>%
                         dplyr::mutate(id = row_number()) 
                       
                       # match edges with names of nodes
                       edges <- edges %>%
                         dplyr::left_join(nodes, by=c("from" = "node")) %>%
                         dplyr::rename(from_name = from) %>%
                         dplyr::rename(from = id) %>%
                         dplyr::rename(from_weight = total_weight) %>%
                         dplyr::rename(from_connections = connections) %>%
                         dplyr::left_join(nodes, by=c("to" = "node")) %>%
                         dplyr::rename(to_name = to) %>%
                         dplyr::rename(to = id) %>%
                         dplyr::rename(to_weight = total_weight) %>%
                         dplyr::rename(to_connections = connections) %>%
                         dplyr::select(from, to, from_name, to_name, weight, from_weight, to_weight, from_connections, to_connections) %>%
                         filter(!is.na(from)) %>%
                         filter(!is.na(to)) 
                       
                       # putin the proper order
                       edges <- edges %>% 
                         dplyr::mutate(from = as.integer(from)) %>%
                         dplyr::mutate(to = as.integer(to)) %>% 
                         dplyr::select(from, to, from_name, to_name, weight, from_weight, to_weight, from_connections, to_connections) 
                       edges
                     }
    
    setwd("~projects/data")
    write_csv(edges, paste0(cat1, "_pairwise_edges_", firstyear, "-", lastyear))
    allresults <- rbind(allresults, edges)
  }

setwd("~projects/data")
write_csv(allresults, paste0(cat1, "_pairwise_edges.csv"))

edges <- read_csv(paste0(cat1, "_pairwise_edges.csv"))

# extract node information from edges record
n1 <- edges %>% distinct(to_name, to_weight, to_connections) %>%
  rename(node = to_name, count = to_weight, connections = to_connections)
n2 <- edges %>% distinct(from_name, from_weight, from_connections) %>%
  rename(node = from_name, count = from_weight, connections = from_connections)

# add up totals for all decades
edges <- edges %>% group_by(from_name, to_name) %>%
  summarize(weight = sum(weight)) %>%
  ungroup()

nodes <- rbind(n1, n2) %>%
  group_by(node) %>%
  summarize(count = sum(count), 
            connections = sum(connections))

# add id numbers to nodes
nodes <- nodes %>%
  mutate(id = row_number()) 

attr(edges, "spec") <- NULL
#attr(edges, "groups") <- NULL

# match edges with names of nodes
edges <- edges %>% 
  left_join(nodes, by=c("from_name" = "node")) %>%
  dplyr::rename(from = id) %>%
  select(from, from_name, to_name, weight)
edges <- edges %>%
  left_join(nodes, by=c("to_name" = "node")) %>%
  dplyr::rename(to = id) 

edges <- edges %>%
  select(from, to, from_name, to_name, weight) %>%
  filter(!is.na(from)) %>%
  filter(!is.na(to)) 

# putin the proper order
edges <- edges %>% 
  mutate(from = as.integer(from)) %>%
  mutate(to = as.integer(to)) %>% 
  select(from, to, from_name, to_name, weight)

# save those files because generating them takes forever
setwd("~projects/data")
write_csv(edges, paste0(cat1,"-", target, "-edges.csv"))
write_csv(nodes, paste0(cat1, "-", target, "-nodes.csv"))

closeAllConnections()

}


if(target == "debate"){
  #### import results and turn into a network.
  # import results and limit to those in classifier
  terms <- df %>%
    distinct(speechdate, debate_id, sentence_id, term, count) %>%
    group_by(sentence_id, term) %>%
    dplyr::summarize(count = sum(count)) %>%
    ungroup() %>%
    ungroup() 
  
  uniqueterms <- df %>%
    group_by(term) %>% 
    sample_n(1) %>% ungroup() %>%
    select(term, kind, geography, empire) 
  
  termsinpairs <- terms %>%
    dplyr::group_by(sentence_id) %>%
    dplyr::mutate(numterms = dplyr::n()) %>%
    dplyr::ungroup() %>%
    dplyr::filter(numterms > 1) %>%
    select(-numterms)
  
  # get pairwise counts
  # assemble a tibble with all the pairs
  pairs1 <- termsinpairs %>% 
    # mutate(edgeid = paste0(debate, "-", speechdate)) %>%
    # select(edgeid, term) %>%
    group_by(sentence_id) %>% 
    expand(sentence_id, from = term, to = term) %>% 
    filter(from < to) %>%
    ungroup()
  
  nodes <- uniqueterms %>% 
    left_join(terms) %>% #rbind(results1, results2) %>% 
    # group_by(term) %>% sample_n(1) %>% ungroup() %>%
    group_by(kind, empire, geography, term) %>%
    summarize(count = sum(count)) %>%
    #rename(node = term) %>%
    arrange(desc(count)) %>% ungroup() %>% ungroup() 
  
  # create edges
  edges <- pairs1 %>%
    filter(!is.na(from)) %>%
    filter(!is.na(to)) %>%
    count(from, to) %>%
    rename(weight = n) %>%
    filter(weight > 0) %>%
    filter((from %in% uniqueterms$term)&(to %in% uniqueterms$term))
  
  # count connections
  connections <- edges %>%
    group_by(from) %>%
    summarize(connections = n(), total_weight = sum(weight)) %>%
    rename(node = from)
  
  # retain only the nodes that are in edge pairs
  nodes <- nodes %>% rename(node = term) %>%
    filter((node %in% edges$from)|(node %in% edges$to))
  
  nodes <- nodes %>% left_join(connections) %>%
    filter(connections > 0) %>%
    filter(total_weight > 0)
  
  # only the nodes that are in edge pairs
  nodes <- nodes %>% filter((node %in% edges$from)|(node %in% edges$to))%>%
    arrange(desc(count)) %>%
    filter(!is.na(node)) %>%
    filter(count > 0)  %>%
    mutate(id = row_number())
  
  # add id numbers to nodes
  nodes <- nodes %>%
    mutate(id = row_number()) 
  
  # match edges with names of nodes
  edges <- edges %>%
    left_join(nodes, by=c("from" = "node")) %>%
    rename(from_name = from) %>%
    rename(from = id) %>%
    rename(from_weight = total_weight) %>%
    rename(from_connections = connections) %>%
    left_join(nodes, by=c("to" = "node")) %>%
    rename(to_name = to) %>%
    rename(to = id) %>%
    rename(to_weight = total_weight) %>%
    rename(to_connections = connections) %>%
    select(from, to, from_name, to_name, weight, from_weight, to_weight, from_connections, to_connections) %>%
    filter(!is.na(from)) %>%
    filter(!is.na(to)) 
  
  # putin the proper order
  edges <- edges %>% 
    mutate(from = as.integer(from)) %>%
    mutate(to = as.integer(to)) %>% 
    select(from, to, from_name, to_name, weight, from_weight, to_weight, from_connections, to_connections)
  
}



write_csv(edges, paste0(cat1, "_pairwise_edges.csv"))

